# Generated by Django 5.2.4 on 2025-07-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsrecord',
            name='accelerator_pedal_position',
            field=models.IntegerField(blank=True, help_text='IO082: Accelerator pedal position %', null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='engine_rpm_can',
            field=models.IntegerField(blank=True, help_text='IO085: Engine RPM (CAN)', null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='fuel_level_can',
            field=models.IntegerField(blank=True, help_text='IO089: Fuel level (CAN) % or L', null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='security_state_flags',
            field=models.BigIntegerField(blank=True, help_text='IO132: Security state flags bit-field', null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='total_mileage_can',
            field=models.BigIntegerField(blank=True, help_text='IO087: Total mileage (CAN) in meters', null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='total_mileage_counted',
            field=models.BigIntegerField(blank=True, help_text='IO105: Total mileage counted in meters', null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='vehicle_speed_can',
            field=models.IntegerField(blank=True, help_text='IO081: Vehicle speed (CAN) km/h', null=True),
        ),
    ]
