# Generated by Django 5.2.4 on 2025-07-08 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_data', '0002_gpsrecord_accelerator_pedal_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('digital_output', 'Digital Output Stream'), ('can_control', 'CAN Control Stream')], max_length=20)),
                ('command_name', models.CharField(help_text='lock, unlock, mobilize, immobilize', max_length=20)),
                ('command_text', models.CharField(help_text='The actual command sent to device', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('device_response', models.TextField(blank=True, help_text='Response received from device', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='gps_data.device')),
            ],
            options={
                'db_table': 'device_commands',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'created_at'], name='device_comm_device__46d6a1_idx'), models.Index(fields=['status'], name='device_comm_status_dc8019_idx'), models.Index(fields=['command_type', 'command_name'], name='device_comm_command_e44737_idx'), models.Index(fields=['created_at'], name='device_comm_created_748a2b_idx')],
            },
        ),
    ]
