# Generated by Django 5.2.4 on 2025-07-08 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps_data', '0003_devicecommand'),
    ]

    operations = [
    ]
