# Generated by Django 5.2.4 on 2025-07-06 13:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProcessingStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_imei', models.CharField(db_index=True, max_length=20)),
                ('packet_data', models.TextField()),
                ('processing_attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_processing_status',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['processed', 'processing_attempts'], name='data_proces_process_95aec0_idx'), models.Index(fields=['device_imei', '-created_at'], name='data_proces_device__c69f12_idx')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imei', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['imei'], name='devices_imei_fa0ada_idx'), models.Index(fields=['is_active'], name='devices_is_acti_9ea4e7_idx'), models.Index(fields=['last_seen'], name='devices_last_se_cc30d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_devices', models.IntegerField(default=0)),
                ('active_devices', models.IntegerField(default=0)),
                ('devices_last_24h', models.IntegerField(default=0)),
                ('total_records', models.BigIntegerField(default=0)),
                ('records_last_24h', models.BigIntegerField(default=0)),
                ('records_last_hour', models.BigIntegerField(default=0)),
                ('successful_packets', models.BigIntegerField(default=0)),
                ('failed_packets', models.BigIntegerField(default=0)),
                ('processing_errors', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'system_stats',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='system_stat_timesta_de2992_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_timestamp', models.DateTimeField(db_index=True)),
                ('server_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('altitude', models.IntegerField(blank=True, null=True)),
                ('angle', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('satellites', models.IntegerField(blank=True, null=True)),
                ('ignition', models.BooleanField(blank=True, null=True)),
                ('movement', models.BooleanField(blank=True, null=True)),
                ('gsm_signal', models.IntegerField(blank=True, null=True)),
                ('gnss_status', models.IntegerField(blank=True, null=True)),
                ('external_voltage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('battery_voltage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('battery_current', models.IntegerField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('total_odometer', models.BigIntegerField(blank=True, null=True)),
                ('io_data', models.JSONField(blank=True, default=dict)),
                ('raw_packet', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_data', to='tracking.device')),
            ],
            options={
                'db_table': 'telemetry_data',
                'ordering': ['-device_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ignition_on', 'Ignition On'), ('ignition_off', 'Ignition Off'), ('movement_start', 'Movement Started'), ('movement_stop', 'Movement Stopped'), ('overspeed', 'Over Speed'), ('geofence_enter', 'Geofence Enter'), ('geofence_exit', 'Geofence Exit'), ('low_battery', 'Low Battery'), ('connection_lost', 'Connection Lost'), ('connection_restored', 'Connection Restored'), ('alarm', 'Alarm Triggered'), ('crash', 'Crash Detected'), ('jamming', 'Signal Jamming')], db_index=True, max_length=20)),
                ('event_time', models.DateTimeField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.device')),
                ('telemetry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.telemetrydata')),
            ],
            options={
                'db_table': 'device_events',
                'ordering': ['-event_time'],
            },
        ),
        migrations.AddIndex(
            model_name='telemetrydata',
            index=models.Index(fields=['device', '-device_timestamp'], name='telemetry_d_device__fb03d5_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrydata',
            index=models.Index(fields=['device', '-server_timestamp'], name='telemetry_d_device__bc775e_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrydata',
            index=models.Index(fields=['-device_timestamp'], name='telemetry_d_device__14b6f4_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrydata',
            index=models.Index(fields=['-server_timestamp'], name='telemetry_d_server__c62c39_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrydata',
            index=models.Index(fields=['ignition'], name='telemetry_d_ignitio_eaea76_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrydata',
            index=models.Index(fields=['movement'], name='telemetry_d_movemen_b40ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrydata',
            index=models.Index(fields=['latitude', 'longitude'], name='telemetry_d_latitud_a55855_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrydata',
            index=models.Index(fields=['device', 'ignition', '-device_timestamp'], name='telemetry_d_device__5bc5e1_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrydata',
            index=models.Index(fields=['device', 'movement', '-device_timestamp'], name='telemetry_d_device__f101b9_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['device', '-event_time'], name='device_even_device__239109_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['event_type', '-event_time'], name='device_even_event_t_9261f2_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['device', 'event_type', '-event_time'], name='device_even_device__aa7bcc_idx'),
        ),
    ]
